apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: alexkalinck-dev
data:
  KAFKA_PLAINTEXT_PORT: "9092"
  KAFKA_PLAINTEXT_HOST_PORT: "29092"
  KAFKA_CONTROLLER_PORT: "29093"
  KAFKA_ENABLE_KRAFT: "yes"
  KAFKA_CFG_PROCESS_ROLES: "broker,controller"
  KAFKA_CFG_NODE_ID: "1"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:29093"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-gateway:9092,PLAINTEXT_HOST://localhost:29092"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka-gateway:29093"
  KAFKA_KRAFT_CLUSTER_ID: "r4zt_wrqTRuT7W2NJsB_GA"
  ALLOW_PLAINTEXT_LISTENER: "yes"