apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: microservices
type: Opaque
stringData:
  AUTHENTICATION_SERVICE_DB_PASSWORD: "authpassword"
  SPRING_DATASOURCE_URL: "jdbc:mysql://auth-db:3306/authdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
  AUTHENTICATION_SERVICE_DB_USER: "root"