apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
  namespace: microservices
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "orderpassword"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_URL: "jdbc:mysql://order-db:3306/orderdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"

