apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
  namespace: microservices
type: Opaque
stringData:
  MONGO_INITDB_ROOT_PASSWORD: "secret"
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_DB_URI: "mongodb://root:secret@mongodb:27017/mydatabase?authSource=admin"


