apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: microservices
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "wtpassword"
  SPRING_DATASOURCE_URL: "jdbc:mysql://user-db:3306/userdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
  USER_SERVICE_DB_USER: "root"

