server:
  port: ${API_GATEWAY_PORT:8083}

logging:
  level:
    org.springframework.cloud.gateway : debug
    org.springframework.security.web.server.WebFilterChainProxy: DEBUG
    org.springframework.security.web.server.csrf: TRACE
    org.springframework.security.web.server.authentication: TRACE
    org.springframework.security.web.server.authorization: TRACE

spring:
  profiles:
    active: ${API_GATEWAY_PROFILE:dev}
  config:
    import:
      - optional:file:.env
      - classpath:routes.yml
      - classpath:error-message.properties
  application:
    name: ApiGateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-user
              uri: ${USER_SERVICE_URL:http://localhost:8080}
              predicates:
                - Path=/user/**
            - id: user-service-cardInfo
              uri: ${USER_SERVICE_URL:http://localhost:8080}
              predicates:
                - Path=/cardInfo/**
            - id: auth-service
              uri: ${AUTHENTICATION_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/auth/**
            - id: order-service-order
              uri: ${ORDER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/order/**
            - id: order-service-item
              uri: ${ORDER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/item/**
            - id: payment-service
              uri: ${PAYMENT_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/payment/**

