services:
  user:
    url: ${USER_SERVICE_URL:http://localhost:8080}
    base_endpoint: /user
    endpoints:
      create: /create
      getByEmail: /email/{email}
      getById: /{id}
      update: /update
      delete: /{id}

  order:
    url: ${ORDER_SERVICE_URL:http://localhost:8082}
    base_endpoint: /order
    endpoints:
      create: /create
      get: /{id}
      update: /update
      delete: /{id}

  auth:
    url: ${AUTHENTICATION_SERVICE_URL:http://localhost:8081}
    base_endpoint: /auth
    endpoints:
      validate: /validate
      register: /register
      login: /login
      refresh: /refresh
      delete: /{id}

  item:
    url: ${ITEM_SERVICE_URL:http://localhost:8082}
    base_endpoint: /item
    endpoints:
      create: /create
      get: /{id}
      update: /update
      delete: /{id}

  cardInfo:
    url: ${CARD_SERVICE_URL:http://localhost:8080}
    base_endpoint: /cardInfo
    endpoints:
      create: /create
      get: /{id}
      update: /update
      delete: /{id}
  api-gateway:
    url: ${API_GATEWAY_URL:http://localhost:8083}
    base_endpoint: /api-gateway
    endpoints:
      registration: /register
      login: /login
  frontend:
    url: ${FRONTEND_URL:http://localhost}
