apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userdb-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          resources:
            requests:
              cpu: "200m"
              memory: "100Mi"
            limits:
              cpu: "300m"
              memory: "100Mi"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "userdb"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-secrets
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: userdb-pvc
  serviceName: user-db
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: microservices
spec:
  clusterIP: None
  selector:
    app: user-db
  ports:
    - port: 3306
      targetPort: 3306
