apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: microservices
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: api-gateway-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-gateway
        app.kubernetes.io/component: gateway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000

      terminationGracePeriodSeconds: 30

      containers:
        - name: api-gateway
          image: apigateway-api-gateway:1.0
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          ports:
            - name: http
              containerPort: 8083
              protocol: TCP

          env:
            - name: SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: SERVER_ADDRESS
            - name: API_GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: API_GATEWAY_URL
            - name: API_GATEWAY_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: API_GATEWAY_PORT
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: API_GATEWAY_PROFILE
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: USER_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: ORDER_SERVICE_URL
            - name: AUTHENTICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: AUTHENTICATION_SERVICE_URL

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: microservices
  labels:
    app.kubernetes.io/name: api-gateway
spec:
  selector:
    app.kubernetes.io/name: api-gateway
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
