---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authdb-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: microservices
  labels:
    app: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE
              value: "authdb"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: AUTHENTICATION_SERVICE_DB_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: authdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: microservices
  labels:
    app: auth-db
spec:
  selector:
    app: auth-db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
