---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authdb-pvc
  namespace: alexkalinck-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
  namespace: alexkalinck-dev
  labels:
    app: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "300m"
              memory: "1Gi"
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE
              value: "authdb"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_INNODB_BUFFER_POOL_SIZE
              value: "256M"
            - name: MYSQL_INNODB_LOG_FILE_SIZE
              value: "128M"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: authdb-pvc
  serviceName: auth-db
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: alexkalinck-dev
spec:
  clusterIP: None
  selector:
    app: auth-db
  ports:
    - port: 3306
      targetPort: 3306