apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: microservices
data:
  AUTHENTICATION_SERVICE_URL: "http://order-service:8081"
  SPRING_APPLICATION_PORT: "8081"
  SPRING_APPLICATION_ADDRESS: "0.0.0.0"
  CORS_ALLOWED_ORIGIN_PATTERN: "http://localhost:*"
  CORS_ALLOWED_ORIGIN_PATTERN_SPLITTER: ","
