apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderdb-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "orderdb"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-service-secrets
                  key: ORDER_SERVICE_DB_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: orderdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: order-db
  ports:
    - port: 3306
      targetPort: 3306
