apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: microservices
data:
  ORDER_SERVICE_URL: "http://order-service:8082"
  ITEM_SERVICE_URL: "http://order-service:8082"
  ORDER_SERVICE_PORT: "8082"
  ORDER_SERVICE_PROFILE: "docker"
  SERVER_ADDRESS: "0.0.0.0"

