apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: microservices
data:
  PAYMENT_SERVICE_PORT: "8085"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-gateway-headless:9092"
  RANDOM_API_URI: "https://www.randomnumberapi.com/api/v1.0/random"
