apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment
          image: apigateway-payment-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
              name: http
          envFrom:
            - configMapRef:
                name: payment-service-config
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-service-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-service-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_DB_URI
              valueFrom:
                secretKeyRef:
                  name: payment-service-secrets
                  key: MONGO_DB_URI
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: PAYMENT_SERVICE_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: microservices
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
  type: ClusterIP